language: c
sudo: false
dist: bionic
os:
  - linux
#  - osx
addons:
  apt:
    packages:
      - texinfo
      - texlive
      - libxml2
      - python-libxml2
      - swig
      - help2man
      - libpcre2-dev
      - libpcre2-32-0
      - libconvert-binary-c-perl
matrix:
  fast_finish: true
  include:
    #- compiler: gcc
    #  env: ASAN=1 CONF="--disable-bindings"
    - compiler: gcc
      env: DISTCHECK=1 CONF="--enable-release"
    #- compiler: gcc
    #  env: CONF="--enable-trace"
      #addons:
      #  apt:
      #    packages:
      #      - valgrind
    #- compiler: clang

branches:
  except:
    - appveyor
    - /^work/

install:
  - sh autogen.sh

script:
  - if [ -n "$ASAN" ]; then
      CLANG="-O0 -fno-omit-frame-pointer -fsanitize=address,undefined -fno-var-tracking" ;
    fi
  - ./configure $CONF
    # ASAN started swapping with only 8GB
  - if [ -n "$ASAN" ]; then
        travis_wait make -C src encode.lo ;
        travis_wait make -C src decode.lo ;
        travis_wait make -j4 -C src ;
        make -j4 ;
    else
        make -j4 ;
    fi
    # ASAN just became too slow. skip unit-tests there.
  - if [ -n "$DISTCHECK" ]; then
      travis_wait 30 make -j4 distcheck && sha256sum libredwg-*.tar.* ;
    else
      if [ -n "$ASAN" ]; then
        make -j4 check -C src ;
        travis_wait make -j4 check -C programs ;
        travis_wait make -j4 check-minimal -C test/unit-testing/ ;
      else
        make -j4 check ;
      fi
    fi

deploy:
  provider: releases
  file_glob: true
  file: libredwg-*.tar.*
  api_key:
    secure: "C86usbAdSxmRlFIwteeK+dyu7xASSG4y+jLpvipg/cw8SnRTkwWMIwmzXgbqA5uuskGs4jxyK0OKzrobg4KqnNUNa9wxJ/nLPFi9JxKDLwb9YxskoWigfYbdsXz/unU6XZ6giAsAbjiZQpgTl70DDlk9d1adQQGSkUb5CT6xmlmBuFF+OFubVNtMC3rhQoICS4O5a3uo5+qyY/FUjWJK39h5PfxUCW1VCrD2kuW8uoITKBmc/FAAxydFppwelKLMaI2B4O6pwpV0DBwTKhx6l/uQufDzwC8//hyDLmK7rcIy66YNVKUt/y+cwrpXgzlKsjvqNuHyeGE8N6alwBNU59g0QBJ1h+46aO8SSwRFHPLyLBkN2KY1VvaPTB2I0QYYoUAaACwXVcYpp1hb8RYRLNM6VCByeDhlTZNO9H2Nin2k1kqeGtnVYDbdKgPQL0cXpj4OKKDJlbNjv2hMVW0MPx92GaoXDhI3HfmmV66Qf4OyJT5rnX01kxeYzlkByUkG1i4FGB0xyg1OZSHd7B17KgPr0suVz0f9N2mFN1dGzp2O2alFwRl3GIpgCoAOlwsz5nJs55IqCOyaTvk7Zyh2PkeF6GKgFC2zgLL9g5D58+ZFulTojp5lshbOTepgvj3Oo+1rNoa6ke9F5Jvi0KOtVYM/z2wapr3pTa7bYcJK/lg="
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    condition: $DISTCHECK = 1
